[workspace]
members = ["ctreg", "ctreg-demo", "ctreg-macro"]
resolver = "2"

[workspace.dependencies]
regex-automata = { version = "0.4.6", default-features = false }
regex-syntax = { version = "0.8.2", default-features = false }
thiserror = { version = "1.0.59" }
